### ISSUE TITLE
Active record configuration issue

### ISSUE THREAD

**Issue by wyao905** [learn-co-curriculum/activerecord-tvland#23]
Every time rake db:migrate is run, this issue occurs
```
DEPRECATION WARNING: Setting `ActiveRecord::Base.configurations` with `[]=` is deprecated. Use `ActiveRecord::Base.configurations=` directly to set the configurations instead. (called from require at /home/reliable-dispatch-3211/activerecord-tvland-online-web-sp-000/config/environment.rb:3)
rake aborted!
```
Unable to complete the lab due to this issue. As a result, will skip this lab.

**Comment by maxwellbenton** [comment]
Hi @wyao905,

Thank you for opening this issue. I was unable to reproduce the error that you experienced, but it looks like a recent update to ActiveRecord introduced some issues into this lab. We've taken a look and updated the Gemfile, as well as the solution and confirmed that `rake db:migrate` should now be working.

Please note, if you experience an issue like this where you are unable to get past an error that may be due to an issue with the lab itself, we recommend you use the [Ask a Question](http://help.learn.co/ask-a-question/where-can-i-ask-a-question-about-a-lesson) (AAQ) feature to get assistance before moving on.

If you would like to complete this lab with the updates, you will need to delete your existing personal fork of the repository, and either revisit the lesson in Learn or visit the learn-co-student repository to refork the lab.

Thank you for contributing to a Learn lesson! If you are still experiencing this error, please reopen this issue.
